[project]
name = "vtasca-github-io"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "markdown2>=2.5.3",
    "notion-client>=2.3.0",
    "notion2md>=2.9.0",
    "python-dotenv>=1.0.1",
]
